{
    'name': 'Inmoser Service Order',
    'version': '17.0.1.0.0',
    'category': 'Service Management',
    'summary': 'Service Order Management for Inmoser',
    'author': 'INMOSER84',
    'website': 'https://github.com/INMOSER84/inmoser_service_order',
    'license': 'LGPL-3',
    'depends': ['base', 'web', 'mail', 'account', 'stock', 'hr', 'portal'],
    'data': [
        'security/ir.model.access.csv',
        'security/inmoser_security.xml',
        'data/service_type_data.xml',
        'data/ir_sequence_data.xml',
        'data/cron_jobs.xml',
        'data/email_templates.xml',
        'views/menu_items.xml',
        'views/service_order_views.xml',
        'views/service_order_actions.xml',
        'views/service_order_calendar.xml',
        'views/service_equipment_views.xml',
        'views/service_type_views.xml',
        'views/hr_employee_views.xml',
        'views/res_partner_views.xml',
        'views/portal_templates.xml',
        'views/service_complete_wizard_views.xml',
        'views/service_reprogram_wizard_views.xml',
        'reports/service_order_report.xml',
        'reports/service_order_template.xml',
        'reports/service_certificate_template.xml',
        'reports/equipment_history_template.xml',
        'reports/technician_performance_template.xml',
        'static/src/xml/service_order_qr.xml',
        'static/src/xml/calendar_templates.xml',
    ],
    'demo': ['demo/demo_data.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'external_dependencies': {'python': ['qrcode']},
    'development_status': 'Beta',
    'price': 0,
    'currency': 'EUR',
}
